version: '3.5'  

services: 
   docker-backend-2.6: 
      image: backend
      ports: 
        - 8000:8000
      volumes: 
        - ${PWD}/logs.txt:/usr/local/www/backend/logs.txt
      environment:
        - REDIS=localhost
        - REDIS_PORT=6379
        - DB_USERNAME=admin
        - DB_PASSWORD=pasw0rd
        - DB_HOST=database
        - A_URL=http://localhost:5000
      restart: unless-stopped
    redis: 
      image: redis:alpine
    db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=admin
        - POSTGRES_USER=pasw0rd
    docker-front-2.6:
      image: frontend
      ports:
        - 5000:5000
      environment:
        - B_URL=http://localhost:8000