version: '3.5'

services:
  frontend: 
    build: 
      context: ml-kurkkumopo-frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
  backend:
    volumes:
      - models:/src/model
    build: 
      context: ml-kurkkumopo-backend
      dockerfile: Dockerfile
    depends_on: 
      - training
    ports:
      - 5000:5000
   training:
      context: ml-kurkkumopo-training
      dockerfile: Dockerfile
    volumes:
      - models:/src/model
      - images:/src/imgs
